version: '3.3'
services:
  localserver:
    build: container
    volumes:
      - ./app:/app
    ports:
      - 80:8080
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 --reload app.main:api
    tty: true